export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIE_DVD_RELEASE = 'FETCH_MOVIE_DVD_RELEASE';
export const FETCH_MOVIE_DVD_RELEASE_SUCCESS = 'FETCH_MOVIE_DVD_RELEASE_SUCCESS';
export const FETCH_MOVIE_DVD_RELEASE_FAILURE = 'FETCH_MOVIE_DVD_RELEASE_FAILURE';

export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const RESET_SEARCH_QUERY = 'RESET_SEARCH_QUERY';

export const ADD_SAVED_MOVIE = 'ADD_SAVED_MOVIE';
export const REMOVE_SAVED_MOVIE = 'REMOVE_SAVED_MOVIE';
